name: Github action pour Axel

on:
  push:
    branches: [ "Axel" ]
  pull_request:
    branches: [ "Axel" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Récupération du code
        uses: actions/checkout@v4

      - name: 2. Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 3. Installation des outils (Versions figées)
        run: |
          python -m pip install --upgrade pip
          # On fige les versions pour éviter des cassures inattendues du pipeline
          pip install bandit==1.7.7 pip-audit==2.7.3 ruff==0.3.4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 4. Audit des dépendances (Pip-audit)
        run: pip-audit -r requirements.txt

      - name: 5. Analyse de sécurité (Bandit)
        run: bandit -r . -v -x ./templates

      - name: 6. Vérification de la propreté du code (Ruff)
        run: ruff check .

      - name: 7. Connexion à Docker Hub
        # Utilisation de secrets pour masquer les identifiants
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 8. Construction et Push de l'image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Double tag : 'latest' pour l'usage courant, et le 'SHA' pour la traçabilité
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devsecops_2_guardia:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devsecops_2_guardia:${{ github.sha }}